version: '3.8'

networks:
  default:
    driver: bridge

services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./api/:/api
    # command:
      # ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always 
    networks:
      - default
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
volumes:
  postgres_data: